### ISSUE TITLE
NullPointerException on server Start

### ISSUE THREAD

**Issue by vulgarfate** [Firestar311/Enforcer#1]
I can't really read Java errors, but it seems there's nothing else involved with the error except for Paper/Bukkit itself, and the Enforcer plugin, meaning no other plugin is interacting (I hope!):
https://pastebin.com/pwcS6rc2

**Comment by Firestar311** [comment]
Um... I did not receive a notification about this issue, even though I have them enabled for all of my projects on this site (Weird huh?)

Anyways, I have had several releases of this plugin since you posted this issue. Please grab those and tell me if you have any more issues

Just a note: I do test these and I have not had these issues, you mentioned Paper and I do not support that, only Spigot itself. If you have these issues on the latest version, please try using Spigot then.

**Comment by Firestar311** [comment]
I am going to close this issue as you have not commented past your original and I assume that the latest release has fixed it
